/**
 * SEED / DEMO DATA — not production CMS content.
 * Used until Firestore is populated from admin.
 */
import type { DeliveryZone } from "@/domains/delivery/models";
import { DEFAULT_OPENING_HOURS } from "@/domains/fulfillment/hours";
import type { MenuCategory, MenuItem, ModifierGroup, PricingCalendar } from "@/domains/menu/models";
import type { InventoryItem } from "@/domains/inventory/models";
import type { Weekday } from "@/lib/time";

export const SEED_SOURCE = "demo-seed" as const;
export const SEED_RESTAURANT_ID = "uppsala-main";

const STAMP = "2026-01-01T00:00:00.000Z";
const ALL_DAYS: Weekday[] = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

export const seedRestaurant = {
  id: SEED_RESTAURANT_ID,
  name: "Meridian Fusion Cuisine",
  city: "Uppsala",
  country: "SE",
  timeZone: "Europe/Stockholm" as const,
  pickup: {
    line1: "Kungsängsgatan 1",
    postalCode: "75322",
    city: "Uppsala",
    country: "SE",
  },
  openingHours: DEFAULT_OPENING_HOURS,
  orderingPaused: false,
  kitchenCapacityPer15Min: 10,
  seed: true,
};

export const seedPricingCalendar: PricingCalendar = {
  timeZone: seedRestaurant.timeZone,
  weekendDays: ["saturday", "sunday"],
};

export const seedCategories: MenuCategory[] = [
  {
    id: "plates",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Today's plates",
    slug: "plates",
    description: "Weekday plates from 129 SEK. Weekend pricing is calculated on the server.",
    displayOrder: 1,
    createdAt: STAMP,
    updatedAt: STAMP,
  },
  {
    id: "sides",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Sides",
    slug: "sides",
    displayOrder: 2,
    createdAt: STAMP,
    updatedAt: STAMP,
  },
  {
    id: "drinks",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Drinks",
    slug: "drinks",
    displayOrder: 3,
    createdAt: STAMP,
    updatedAt: STAMP,
  },
];

function plate(
  partial: Omit<MenuItem, "restaurantId" | "currency" | "availableDays" | "createdAt" | "updatedAt" | "isAvailable">,
): MenuItem {
  return {
    restaurantId: SEED_RESTAURANT_ID,
    currency: "SEK",
    availableDays: ALL_DAYS,
    isAvailable: true,
    createdAt: STAMP,
    updatedAt: STAMP,
    ...partial,
  };
}

export const seedMenuItems: MenuItem[] = [
  plate({
    id: "jollof",
    slug: "jollof-rice",
    name: "Jollof Rice",
    shortDescription: "Smoky Ghanaian jollof",
    description:
      "One-pot tomato rice cooked down with onion, ginger and scotch bonnet. Served with your protein and shito.",
    images: [],
    categoryId: "plates",
    basePriceOre: 12900,
    weekdayPriceOre: 12900,
    weekendPriceOre: 14900,
    isFeatured: true,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "jollof",
    availableQuantity: 30,
    lowStockThreshold: 5,
    preparationTimeMinutes: 25,
    allergens: [],
    dietaryTags: ["HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "rice", grams: 350 },
      { name: "protein", grams: 150 },
      { name: "shito", grams: 20 },
    ],
    displayOrder: 1,
  }),
  plate({
    id: "waakye",
    slug: "waakye",
    name: "Waakye",
    shortDescription: "Rice and beans, Accra style",
    description: "Rice and beans steamed with millet leaves, served with salad, spaghetti and your protein.",
    images: [],
    categoryId: "plates",
    basePriceOre: 12900,
    weekdayPriceOre: 12900,
    weekendPriceOre: 14900,
    isFeatured: true,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "waakye",
    availableQuantity: 24,
    lowStockThreshold: 5,
    preparationTimeMinutes: 25,
    allergens: ["EGG", "GLUTEN"],
    dietaryTags: ["HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "rice and beans", grams: 350 },
      { name: "protein", grams: 150 },
    ],
    displayOrder: 2,
  }),
  plate({
    id: "red-red",
    slug: "red-red",
    name: "Red Red",
    shortDescription: "Bean stew and plantain",
    description: "Black-eyed bean stew in palm oil, finished with crispy fried ripe plantain.",
    images: [],
    categoryId: "plates",
    basePriceOre: 11900,
    weekdayPriceOre: 11900,
    weekendPriceOre: 13900,
    isFeatured: true,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "red-red",
    availableQuantity: 20,
    lowStockThreshold: 4,
    preparationTimeMinutes: 22,
    allergens: [],
    dietaryTags: ["VEGETARIAN", "HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "beans", grams: 280 },
      { name: "plantain", grams: 150 },
    ],
    displayOrder: 3,
  }),
  plate({
    id: "banku-tilapia",
    slug: "banku-tilapia",
    name: "Banku & Tilapia",
    shortDescription: "Grilled tilapia with banku",
    description: "Fermented banku with grilled tilapia, onion and pepper sauce. Limited portions each day.",
    images: [],
    categoryId: "plates",
    basePriceOre: 14900,
    weekdayPriceOre: 14900,
    weekendPriceOre: 16900,
    isFeatured: true,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "tilapia",
    availableQuantity: 10,
    lowStockThreshold: 3,
    preparationTimeMinutes: 30,
    allergens: ["FISH"],
    dietaryTags: ["HALAL", "SPICY"],
    modifierGroupIds: ["heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "banku", grams: 320 },
      { name: "tilapia", grams: 280 },
    ],
    displayOrder: 4,
  }),
  plate({
    id: "banku-okro",
    slug: "banku-okro-soup",
    name: "Banku & Okro Soup",
    shortDescription: "Banku with okro",
    description: "Soft banku with a glossy okro soup. Choose chicken or fish.",
    images: [],
    categoryId: "plates",
    basePriceOre: 13900,
    weekdayPriceOre: 13900,
    weekendPriceOre: 15900,
    isFeatured: false,
    isPopular: false,
    inventoryTracked: true,
    inventorySku: "banku-okro",
    availableQuantity: 18,
    lowStockThreshold: 4,
    preparationTimeMinutes: 28,
    allergens: ["FISH"],
    dietaryTags: ["HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "banku", grams: 320 },
      { name: "okro soup", grams: 300 },
    ],
    displayOrder: 5,
  }),
  plate({
    id: "fufu-light",
    slug: "fufu-light-soup",
    name: "Fufu & Light Soup",
    shortDescription: "Fufu with light soup",
    description: "Pounded fufu with a clear, aromatic light soup. A Sunday classic, available every day.",
    images: [],
    categoryId: "plates",
    basePriceOre: 13900,
    weekdayPriceOre: 13900,
    weekendPriceOre: 15900,
    isFeatured: true,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "fufu-light",
    availableQuantity: 16,
    lowStockThreshold: 4,
    preparationTimeMinutes: 30,
    allergens: [],
    dietaryTags: ["HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "fufu", grams: 300 },
      { name: "soup", grams: 320 },
      { name: "protein", grams: 150 },
    ],
    displayOrder: 6,
  }),
  plate({
    id: "fufu-groundnut",
    slug: "fufu-groundnut-soup",
    name: "Fufu & Groundnut Soup",
    shortDescription: "Fufu with groundnut soup",
    description: "Fufu in a deep, roasted groundnut soup. Please note peanuts.",
    images: [],
    categoryId: "plates",
    basePriceOre: 13900,
    weekdayPriceOre: 13900,
    weekendPriceOre: 15900,
    isFeatured: false,
    isPopular: false,
    inventoryTracked: true,
    inventorySku: "fufu-groundnut",
    availableQuantity: 16,
    lowStockThreshold: 4,
    preparationTimeMinutes: 30,
    allergens: ["PEANUT"],
    dietaryTags: ["HALAL"],
    modifierGroupIds: ["protein", "heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "fufu", grams: 300 },
      { name: "groundnut soup", grams: 320 },
    ],
    displayOrder: 7,
  }),
  plate({
    id: "kenkey-fish",
    slug: "kenkey-fish",
    name: "Kenkey & Fish",
    shortDescription: "Ga kenkey with fried fish",
    description: "Fermented kenkey with fried fish and fresh pepper. A coastal plate.",
    images: [],
    categoryId: "plates",
    basePriceOre: 13900,
    weekdayPriceOre: 13900,
    weekendPriceOre: 15900,
    isFeatured: false,
    isPopular: true,
    inventoryTracked: true,
    inventorySku: "kenkey",
    availableQuantity: 2,
    lowStockThreshold: 3,
    preparationTimeMinutes: 26,
    allergens: ["FISH"],
    dietaryTags: ["HALAL", "SPICY"],
    modifierGroupIds: ["heat", "extras", "drinks"],
    kitchenPortions: [
      { name: "kenkey", grams: 320 },
      { name: "fish", grams: 180 },
    ],
    displayOrder: 8,
  }),
  plate({
    id: "fried-plantain",
    slug: "fried-plantain",
    name: "Fried Plantain",
    shortDescription: "Ripe plantain, fried to order",
    description: "Sweet ripe plantain, fried until the edges caramelise.",
    images: [],
    categoryId: "sides",
    basePriceOre: 4900,
    weekdayPriceOre: 4900,
    weekendPriceOre: 4900,
    isFeatured: false,
    isPopular: true,
    inventoryTracked: false,
    preparationTimeMinutes: 8,
    allergens: [],
    dietaryTags: ["VEGAN", "VEGETARIAN"],
    modifierGroupIds: [],
    kitchenPortions: [{ name: "plantain", grams: 180 }],
    displayOrder: 9,
  }),
  plate({
    id: "sobolo",
    slug: "sobolo",
    name: "Sobolo",
    shortDescription: "Hibiscus cooler",
    description: "Cold hibiscus drink with ginger and citrus.",
    images: [],
    categoryId: "drinks",
    basePriceOre: 3500,
    weekdayPriceOre: 3500,
    weekendPriceOre: 3500,
    isFeatured: false,
    isPopular: true,
    inventoryTracked: false,
    preparationTimeMinutes: 2,
    allergens: [],
    dietaryTags: ["VEGAN"],
    modifierGroupIds: [],
    kitchenPortions: [{ name: "sobolo", grams: 330 }],
    displayOrder: 10,
  }),
  plate({
    id: "malt",
    slug: "malt",
    name: "Malt",
    shortDescription: "Chilled malt drink",
    description: "A cold bottle of malt — the classic plate companion.",
    images: [],
    categoryId: "drinks",
    basePriceOre: 2900,
    weekdayPriceOre: 2900,
    weekendPriceOre: 2900,
    isFeatured: false,
    isPopular: false,
    inventoryTracked: false,
    preparationTimeMinutes: 1,
    allergens: ["GLUTEN"],
    dietaryTags: ["VEGETARIAN"],
    modifierGroupIds: [],
    kitchenPortions: [{ name: "malt", grams: 330 }],
    displayOrder: 11,
  }),
];

export const seedModifierGroups: ModifierGroup[] = [
  {
    id: "protein",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Protein",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    displayOrder: 1,
    createdAt: STAMP,
    updatedAt: STAMP,
    options: [
      { id: "chicken", name: "Chicken", priceOre: 0, isAvailable: true, allowsQuantity: false, displayOrder: 1 },
      { id: "beef", name: "Beef", priceOre: 1000, isAvailable: true, allowsQuantity: false, displayOrder: 2 },
      { id: "fish", name: "Fish", priceOre: 1500, isAvailable: true, allowsQuantity: false, displayOrder: 3 },
    ],
  },
  {
    id: "heat",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Spice level",
    required: true,
    minSelections: 1,
    maxSelections: 1,
    displayOrder: 2,
    createdAt: STAMP,
    updatedAt: STAMP,
    options: [
      { id: "mild-shito", name: "Mild shito", priceOre: 0, isAvailable: true, allowsQuantity: false, displayOrder: 1 },
      { id: "hot-shito", name: "Hot shito", priceOre: 0, isAvailable: true, allowsQuantity: false, displayOrder: 2 },
    ],
  },
  {
    id: "extras",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Extras",
    required: false,
    minSelections: 0,
    maxSelections: 4,
    displayOrder: 3,
    createdAt: STAMP,
    updatedAt: STAMP,
    options: [
      { id: "extra-chicken", name: "Extra chicken", priceOre: 2500, isAvailable: true, allowsQuantity: true, maxQuantity: 2, displayOrder: 1 },
      { id: "extra-beef", name: "Extra beef", priceOre: 2800, isAvailable: true, allowsQuantity: true, maxQuantity: 2, displayOrder: 2 },
      { id: "extra-fish", name: "Extra fish", priceOre: 3000, isAvailable: true, allowsQuantity: true, maxQuantity: 2, displayOrder: 3 },
      { id: "plantain", name: "Plantain", priceOre: 2500, isAvailable: true, allowsQuantity: true, maxQuantity: 2, displayOrder: 4 },
      { id: "salad", name: "Salad", priceOre: 1500, isAvailable: true, allowsQuantity: false, displayOrder: 5 },
    ],
  },
  {
    id: "drinks",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Drinks",
    required: false,
    minSelections: 0,
    maxSelections: 2,
    displayOrder: 4,
    createdAt: STAMP,
    updatedAt: STAMP,
    options: [
      { id: "drink-sobolo", name: "Sobolo", priceOre: 3500, isAvailable: true, allowsQuantity: false, displayOrder: 1 },
      { id: "drink-malt", name: "Malt", priceOre: 2900, isAvailable: true, allowsQuantity: false, displayOrder: 2 },
    ],
  },
];

export const seedInventory: InventoryItem[] = seedMenuItems
  .filter((item) => item.inventoryTracked && item.inventorySku)
  .map((item) => ({
    sku: item.inventorySku!,
    restaurantId: SEED_RESTAURANT_ID,
    name: item.name,
    availableQuantity: item.availableQuantity ?? 0,
    reservedQuantity: 0,
    lowStockThreshold: item.lowStockThreshold ?? 3,
    tracked: true,
    createdAt: STAMP,
    updatedAt: STAMP,
  }));

export const seedDeliveryZones: DeliveryZone[] = [
  {
    id: "uppsala-centrum",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Uppsala centrum",
    postalCodes: ["75320", "75321", "75322", "75323", "75324", "75325", "75329", "75331", "75332", "75334", "75335", "75337"],
    baseFeeOre: 4900,
    etaMinutes: 35,
    active: true,
    providers: ["mock"],
  },
  {
    id: "uppsala-south",
    restaurantId: SEED_RESTAURANT_ID,
    name: "Södra Uppsala",
    postalCodes: ["75643", "75645", "75646", "75647", "75650", "75651"],
    baseFeeOre: 5900,
    etaMinutes: 45,
    active: true,
    providers: ["mock"],
  },
];

export function seededCatalog(restaurantId: string) {
  return {
    categories: seedCategories.map((category) => ({ ...category, restaurantId })),
    items: seedMenuItems.map((item) => ({ ...item, restaurantId })),
    modifierGroups: seedModifierGroups.map((group) => ({ ...group, restaurantId })),
    inventory: seedInventory.map((item) => ({ ...item, restaurantId })),
    deliveryZones: seedDeliveryZones.map((zone) => ({ ...zone, restaurantId })),
  };
}

export const seedReviews = [
  {
    id: "r1",
    rating: 5,
    name: "Efua A.",
    quote: "The jollof tasted like home — and it arrived hot in Luthagen.",
    demo: true,
  },
  {
    id: "r2",
    rating: 5,
    name: "Jonas L.",
    quote: "Banku and tilapia on a Thursday. We ordered again the same week.",
    demo: true,
  },
  {
    id: "r3",
    rating: 4,
    name: "Ama K.",
    quote: "Clear spice levels, no surprises. The hot shito is actually hot.",
    demo: true,
  },
];
